-- Create Clinics Table
CREATE TABLE public.clinics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  address text NOT NULL,
  phone_number text,
  website_url text,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL
);

-- Set Security (Public Read Access)
ALTER TABLE public.clinics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.clinics FOR SELECT USING (true);

-- Optional: Insert dummy data
INSERT INTO public.clinics (name, address, phone_number, website_url, latitude, longitude) VALUES
('Spine & Ortho Elite Clinic', '123 Wellness Ave, NY', '+1-555-0100', 'https://example.com/spine', 40.7128, -74.0060),
('Back Pain Relief Center', '456 Therapy Lane, CA', '+1-555-0200', 'https://example.com/back', 34.0522, -118.2437);
